In [31]:
from array import *
array_num = array('i', [1, 3, 5, 3, 7, 1, 9, 3])
print("Original array: "+str(array_num))
num_list = array_num.tolist()
print("Convert the said array to an ordinary list with the same items:")
print(num_list)

Original array: array('i', [1, 3, 5, 3, 7, 1, 9, 3])
Convert the said array to an ordinary list with the same items:
[1, 3, 5, 3, 7, 1, 9, 3]


In [32]:
import numpy as np

n_array = np.array([[55, 25, 15],
                    [30, 44, 2],
                    [11, 45, 77]])

print("Numpy Matrix is:")
print(n_array)

trace = np.trace(n_array)


print("\nTrace of given 3X3 matrix:")
print(trace)


Numpy Matrix is:
[[55 25 15]
 [30 44  2]
 [11 45 77]]

Trace of given 3X3 matrix:
176


In [33]:
import numpy as np
x = np.array([[0, 10, 20], [20, 30, 40]])
print("Original array: ")
print(x)
print("Values bigger than 10 =", x[x>10])
print("Their indices are ", np.nonzero(x > 10))

Original array: 
[[ 0 10 20]
 [20 30 40]]
Values bigger than 10 = [20 20 30 40]
Their indices are  (array([0, 1, 1, 1]), array([2, 0, 1, 2]))


In [34]:
a =np.random.randint(2, 10, size=(2,4))
b=np.random.randint(7, 19, size=(2,4))
print(a)

print(b)
c = np.add(a, b)
print(c)

[[7 2 8 2]
 [6 8 6 6]]
[[18  7  8  7]
 [16  7 15 18]]
[[25  9 16  9]
 [22 15 21 24]]


In [35]:
a = np.random.randint(2, 10, size=(2,4))
b= np.mean(a,axis =1)
print(a)
print(b)
Liste = b.tolist()
print(f'List:{Liste}')
index = 0
for i in a :
  index2 =0
  for j in i:
    a[index,index2] -= round(Liste[index])
    index2 += 1
  index += 1
print(a)

[[2 4 4 9]
 [3 9 7 8]]
[4.75 6.75]
List:[4.75, 6.75]
[[-3 -1 -1  4]
 [-4  2  0  1]]


In [36]:
import numpy as np
print("Original matrix:\n")
X = np.random.randint(2, 10, size =(2,19))
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[6 6 6 8 2 5 4 7 7 6 7 5 5 5 9 5 4 2 6]
 [7 4 3 2 8 4 4 2 2 4 5 7 6 8 4 8 9 6 3]]

Subtract the mean of each row of the said matrix:

[[5.52631579]
 [5.05263158]]
